version: '3.5'

services:
  discord-webhook-handler:
    restart: always
    container_name: discord-webhook-container
    build: .
    ports:
      - "6578:3000"
    environment:
      - PORT=${PORT}

      # Discord Webhook 1
      - DISCORD_WEBHOOK_1_NAMESPACE=${DISCORD_WEBHOOK_1_NAMESPACE}
      - DISCORD_WEBHOOK_1_URL=${DISCORD_WEBHOOK_1_URL}

      # Discord Webhook 2
      - DISCORD_WEBHOOK_2_NAMESPACE=${DISCORD_WEBHOOK_2_NAMESPACE}
      - DISCORD_WEBHOOK_2_URL=${DISCORD_WEBHOOK_2_URL}

    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
